# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pwmio_pb2 as pwmio__pb2


class pwmio_serviceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.InitSteer = channel.unary_unary(
        '/pwmio.pwmio_service/InitSteer',
        request_serializer=pwmio__pb2.init_steer_request.SerializeToString,
        response_deserializer=pwmio__pb2.init_steer_reply.FromString,
        )
    self.InitServo = channel.unary_unary(
        '/pwmio.pwmio_service/InitServo',
        request_serializer=pwmio__pb2.init_servo_request.SerializeToString,
        response_deserializer=pwmio__pb2.init_servo_reply.FromString,
        )
    self.Steer = channel.stream_stream(
        '/pwmio.pwmio_service/Steer',
        request_serializer=pwmio__pb2.steer_request.SerializeToString,
        response_deserializer=pwmio__pb2.steer_reply.FromString,
        )
    self.Throttle = channel.stream_stream(
        '/pwmio.pwmio_service/Throttle',
        request_serializer=pwmio__pb2.throttle_request.SerializeToString,
        response_deserializer=pwmio__pb2.throttle_reply.FromString,
        )
    self.Accel = channel.stream_stream(
        '/pwmio.pwmio_service/Accel',
        request_serializer=pwmio__pb2.accel_request.SerializeToString,
        response_deserializer=pwmio__pb2.accel_reply.FromString,
        )


class pwmio_serviceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def InitSteer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InitServo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Steer(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Throttle(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Accel(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_pwmio_serviceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'InitSteer': grpc.unary_unary_rpc_method_handler(
          servicer.InitSteer,
          request_deserializer=pwmio__pb2.init_steer_request.FromString,
          response_serializer=pwmio__pb2.init_steer_reply.SerializeToString,
      ),
      'InitServo': grpc.unary_unary_rpc_method_handler(
          servicer.InitServo,
          request_deserializer=pwmio__pb2.init_servo_request.FromString,
          response_serializer=pwmio__pb2.init_servo_reply.SerializeToString,
      ),
      'Steer': grpc.stream_stream_rpc_method_handler(
          servicer.Steer,
          request_deserializer=pwmio__pb2.steer_request.FromString,
          response_serializer=pwmio__pb2.steer_reply.SerializeToString,
      ),
      'Throttle': grpc.stream_stream_rpc_method_handler(
          servicer.Throttle,
          request_deserializer=pwmio__pb2.throttle_request.FromString,
          response_serializer=pwmio__pb2.throttle_reply.SerializeToString,
      ),
      'Accel': grpc.stream_stream_rpc_method_handler(
          servicer.Accel,
          request_deserializer=pwmio__pb2.accel_request.FromString,
          response_serializer=pwmio__pb2.accel_reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pwmio.pwmio_service', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
