# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pwmio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pwmio.proto',
  package='pwmio',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bpwmio.proto\x12\x05pwmio\"3\n\npwm_status\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\";\n\x0bpwm_payload\x12\r\n\x05\x61ngle\x18\x01 \x01(\x01\x12\x0b\n\x03\x61\x63\x63\x18\x02 \x01(\x01\x12\x10\n\x08throttle\x18\x03 \x01(\x01\"U\n\x12init_steer_request\x12\x12\n\nsteer_type\x18\x01 \x01(\x05\x12\x15\n\rsteer_channel\x18\x02 \x01(\x05\x12\x14\n\x0csteer_revers\x18\x03 \x01(\x08\"5\n\x10init_steer_reply\x12!\n\x06status\x18\x01 \x01(\x0b\x32\x11.pwmio.pwm_status\"U\n\x12init_servo_request\x12\x12\n\nservo_type\x18\x01 \x01(\x05\x12\x15\n\rservo_channel\x18\x02 \x01(\x05\x12\x14\n\x0cservo_revers\x18\x03 \x01(\x08\"5\n\x10init_servo_reply\x12!\n\x06status\x18\x01 \x01(\x0b\x32\x11.pwmio.pwm_status\"\x1e\n\rsteer_request\x12\r\n\x05\x61ngle\x18\x01 \x01(\x01\"0\n\x0bsteer_reply\x12!\n\x06status\x18\x01 \x01(\x0b\x32\x11.pwmio.pwm_status\"$\n\x10throttle_request\x12\x10\n\x08throttle\x18\x01 \x01(\x01\"3\n\x0ethrottle_reply\x12!\n\x06status\x18\x01 \x01(\x0b\x32\x11.pwmio.pwm_status\"\x1e\n\raccel_request\x12\r\n\x05\x61\x63\x63\x65l\x18\x01 \x01(\x01\"0\n\x0b\x61\x63\x63\x65l_reply\x12!\n\x06status\x18\x01 \x01(\x0b\x32\x11.pwmio.pwm_status2\xc9\x02\n\rpwmio_service\x12\x41\n\tInitSteer\x12\x19.pwmio.init_steer_request\x1a\x17.pwmio.init_steer_reply\"\x00\x12\x41\n\tInitServo\x12\x19.pwmio.init_servo_request\x1a\x17.pwmio.init_servo_reply\"\x00\x12\x37\n\x05Steer\x12\x14.pwmio.steer_request\x1a\x12.pwmio.steer_reply\"\x00(\x01\x30\x01\x12@\n\x08Throttle\x12\x17.pwmio.throttle_request\x1a\x15.pwmio.throttle_reply\"\x00(\x01\x30\x01\x12\x37\n\x05\x41\x63\x63\x65l\x12\x14.pwmio.accel_request\x1a\x12.pwmio.accel_reply\"\x00(\x01\x30\x01\x62\x06proto3')
)




_PWM_STATUS = _descriptor.Descriptor(
  name='pwm_status',
  full_name='pwmio.pwm_status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='pwmio.pwm_status.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='pwmio.pwm_status.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='pwmio.pwm_status.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=73,
)


_PWM_PAYLOAD = _descriptor.Descriptor(
  name='pwm_payload',
  full_name='pwmio.pwm_payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angle', full_name='pwmio.pwm_payload.angle', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc', full_name='pwmio.pwm_payload.acc', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='throttle', full_name='pwmio.pwm_payload.throttle', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=134,
)


_INIT_STEER_REQUEST = _descriptor.Descriptor(
  name='init_steer_request',
  full_name='pwmio.init_steer_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steer_type', full_name='pwmio.init_steer_request.steer_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steer_channel', full_name='pwmio.init_steer_request.steer_channel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steer_revers', full_name='pwmio.init_steer_request.steer_revers', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=221,
)


_INIT_STEER_REPLY = _descriptor.Descriptor(
  name='init_steer_reply',
  full_name='pwmio.init_steer_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pwmio.init_steer_reply.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=276,
)


_INIT_SERVO_REQUEST = _descriptor.Descriptor(
  name='init_servo_request',
  full_name='pwmio.init_servo_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='servo_type', full_name='pwmio.init_servo_request.servo_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='servo_channel', full_name='pwmio.init_servo_request.servo_channel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='servo_revers', full_name='pwmio.init_servo_request.servo_revers', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=363,
)


_INIT_SERVO_REPLY = _descriptor.Descriptor(
  name='init_servo_reply',
  full_name='pwmio.init_servo_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pwmio.init_servo_reply.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=418,
)


_STEER_REQUEST = _descriptor.Descriptor(
  name='steer_request',
  full_name='pwmio.steer_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angle', full_name='pwmio.steer_request.angle', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=450,
)


_STEER_REPLY = _descriptor.Descriptor(
  name='steer_reply',
  full_name='pwmio.steer_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pwmio.steer_reply.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=500,
)


_THROTTLE_REQUEST = _descriptor.Descriptor(
  name='throttle_request',
  full_name='pwmio.throttle_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='throttle', full_name='pwmio.throttle_request.throttle', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=538,
)


_THROTTLE_REPLY = _descriptor.Descriptor(
  name='throttle_reply',
  full_name='pwmio.throttle_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pwmio.throttle_reply.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=591,
)


_ACCEL_REQUEST = _descriptor.Descriptor(
  name='accel_request',
  full_name='pwmio.accel_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accel', full_name='pwmio.accel_request.accel', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=623,
)


_ACCEL_REPLY = _descriptor.Descriptor(
  name='accel_reply',
  full_name='pwmio.accel_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pwmio.accel_reply.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=625,
  serialized_end=673,
)

_INIT_STEER_REPLY.fields_by_name['status'].message_type = _PWM_STATUS
_INIT_SERVO_REPLY.fields_by_name['status'].message_type = _PWM_STATUS
_STEER_REPLY.fields_by_name['status'].message_type = _PWM_STATUS
_THROTTLE_REPLY.fields_by_name['status'].message_type = _PWM_STATUS
_ACCEL_REPLY.fields_by_name['status'].message_type = _PWM_STATUS
DESCRIPTOR.message_types_by_name['pwm_status'] = _PWM_STATUS
DESCRIPTOR.message_types_by_name['pwm_payload'] = _PWM_PAYLOAD
DESCRIPTOR.message_types_by_name['init_steer_request'] = _INIT_STEER_REQUEST
DESCRIPTOR.message_types_by_name['init_steer_reply'] = _INIT_STEER_REPLY
DESCRIPTOR.message_types_by_name['init_servo_request'] = _INIT_SERVO_REQUEST
DESCRIPTOR.message_types_by_name['init_servo_reply'] = _INIT_SERVO_REPLY
DESCRIPTOR.message_types_by_name['steer_request'] = _STEER_REQUEST
DESCRIPTOR.message_types_by_name['steer_reply'] = _STEER_REPLY
DESCRIPTOR.message_types_by_name['throttle_request'] = _THROTTLE_REQUEST
DESCRIPTOR.message_types_by_name['throttle_reply'] = _THROTTLE_REPLY
DESCRIPTOR.message_types_by_name['accel_request'] = _ACCEL_REQUEST
DESCRIPTOR.message_types_by_name['accel_reply'] = _ACCEL_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

pwm_status = _reflection.GeneratedProtocolMessageType('pwm_status', (_message.Message,), {
  'DESCRIPTOR' : _PWM_STATUS,
  '__module__' : 'pwmio_pb2'
  # @@protoc_insertion_point(class_scope:pwmio.pwm_status)
  })
_sym_db.RegisterMessage(pwm_status)

pwm_payload = _reflection.GeneratedProtocolMessageType('pwm_payload', (_message.Message,), {
  'DESCRIPTOR' : _PWM_PAYLOAD,
  '__module__' : 'pwmio_pb2'
  # @@protoc_insertion_point(class_scope:pwmio.pwm_payload)
  })
_sym_db.RegisterMessage(pwm_payload)

init_steer_request = _reflection.GeneratedProtocolMessageType('init_steer_request', (_message.Message,), {
  'DESCRIPTOR' : _INIT_STEER_REQUEST,
  '__module__' : 'pwmio_pb2'
  # @@protoc_insertion_point(class_scope:pwmio.init_steer_request)
  })
_sym_db.RegisterMessage(init_steer_request)

init_steer_reply = _reflection.GeneratedProtocolMessageType('init_steer_reply', (_message.Message,), {
  'DESCRIPTOR' : _INIT_STEER_REPLY,
  '__module__' : 'pwmio_pb2'
  # @@protoc_insertion_point(class_scope:pwmio.init_steer_reply)
  })
_sym_db.RegisterMessage(init_steer_reply)

init_servo_request = _reflection.GeneratedProtocolMessageType('init_servo_request', (_message.Message,), {
  'DESCRIPTOR' : _INIT_SERVO_REQUEST,
  '__module__' : 'pwmio_pb2'
  # @@protoc_insertion_point(class_scope:pwmio.init_servo_request)
  })
_sym_db.RegisterMessage(init_servo_request)

init_servo_reply = _reflection.GeneratedProtocolMessageType('init_servo_reply', (_message.Message,), {
  'DESCRIPTOR' : _INIT_SERVO_REPLY,
  '__module__' : 'pwmio_pb2'
  # @@protoc_insertion_point(class_scope:pwmio.init_servo_reply)
  })
_sym_db.RegisterMessage(init_servo_reply)

steer_request = _reflection.GeneratedProtocolMessageType('steer_request', (_message.Message,), {
  'DESCRIPTOR' : _STEER_REQUEST,
  '__module__' : 'pwmio_pb2'
  # @@protoc_insertion_point(class_scope:pwmio.steer_request)
  })
_sym_db.RegisterMessage(steer_request)

steer_reply = _reflection.GeneratedProtocolMessageType('steer_reply', (_message.Message,), {
  'DESCRIPTOR' : _STEER_REPLY,
  '__module__' : 'pwmio_pb2'
  # @@protoc_insertion_point(class_scope:pwmio.steer_reply)
  })
_sym_db.RegisterMessage(steer_reply)

throttle_request = _reflection.GeneratedProtocolMessageType('throttle_request', (_message.Message,), {
  'DESCRIPTOR' : _THROTTLE_REQUEST,
  '__module__' : 'pwmio_pb2'
  # @@protoc_insertion_point(class_scope:pwmio.throttle_request)
  })
_sym_db.RegisterMessage(throttle_request)

throttle_reply = _reflection.GeneratedProtocolMessageType('throttle_reply', (_message.Message,), {
  'DESCRIPTOR' : _THROTTLE_REPLY,
  '__module__' : 'pwmio_pb2'
  # @@protoc_insertion_point(class_scope:pwmio.throttle_reply)
  })
_sym_db.RegisterMessage(throttle_reply)

accel_request = _reflection.GeneratedProtocolMessageType('accel_request', (_message.Message,), {
  'DESCRIPTOR' : _ACCEL_REQUEST,
  '__module__' : 'pwmio_pb2'
  # @@protoc_insertion_point(class_scope:pwmio.accel_request)
  })
_sym_db.RegisterMessage(accel_request)

accel_reply = _reflection.GeneratedProtocolMessageType('accel_reply', (_message.Message,), {
  'DESCRIPTOR' : _ACCEL_REPLY,
  '__module__' : 'pwmio_pb2'
  # @@protoc_insertion_point(class_scope:pwmio.accel_reply)
  })
_sym_db.RegisterMessage(accel_reply)



_PWMIO_SERVICE = _descriptor.ServiceDescriptor(
  name='pwmio_service',
  full_name='pwmio.pwmio_service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=676,
  serialized_end=1005,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitSteer',
    full_name='pwmio.pwmio_service.InitSteer',
    index=0,
    containing_service=None,
    input_type=_INIT_STEER_REQUEST,
    output_type=_INIT_STEER_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='InitServo',
    full_name='pwmio.pwmio_service.InitServo',
    index=1,
    containing_service=None,
    input_type=_INIT_SERVO_REQUEST,
    output_type=_INIT_SERVO_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Steer',
    full_name='pwmio.pwmio_service.Steer',
    index=2,
    containing_service=None,
    input_type=_STEER_REQUEST,
    output_type=_STEER_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Throttle',
    full_name='pwmio.pwmio_service.Throttle',
    index=3,
    containing_service=None,
    input_type=_THROTTLE_REQUEST,
    output_type=_THROTTLE_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Accel',
    full_name='pwmio.pwmio_service.Accel',
    index=4,
    containing_service=None,
    input_type=_ACCEL_REQUEST,
    output_type=_ACCEL_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PWMIO_SERVICE)

DESCRIPTOR.services_by_name['pwmio_service'] = _PWMIO_SERVICE

# @@protoc_insertion_point(module_scope)
